### PR TITLE
Updating SCSS & footer

### PR DESCRIPTION
**Pull request by philippebernou**
Adding SCSS compilation to jekyll instead of gulp
Updating Footer with latest Magento corp version

### CODE REVIEW

**Comment by skolodyazhnyy** [comment]
Does CSS still work? I see you remove theme/CSS, but without it GitHub won't be able to display CSS. Can yoi double check?

**Comment by philippebernou** [comment]
it certainly works in local jekyll - but can fork and test on github

—
Philippe

**Comment by skolodyazhnyy** [comment]
OK I got it, nevermind my comment

**Comment by philippebernou** [comment]
looks like it doesn’t  - just checked github.io  :(

—
Philippe

**Comment by skolodyazhnyy** [comment]
Nope, didn't work https://magento-mcom.github.io/docs/. Can you have a look into https://github.com/blog/1867-github-pages-now-runs-jekyll-2-2-0 and fix it?

**Comment by philippebernou** [comment]
yes on it

—
Philippe

**Pull request merged**
